# Generated by Django 5.1.6 on 2025-03-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ll_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='school',
            new_name='school_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='school',
            new_name='school_id',
        ),
    ]
