# Generated by Django 5.1.6 on 2025-03-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_admin', '0002_rename_school_class_school_id_and_more'),
        ('ll_auth', '0002_customuser_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school_id',
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ll_auth.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='ll_auth.school'),
        ),
    ]
