# Generated by Django 5.1.6 on 2025-05-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
