# Generated by Django 5.1.6 on 2025-05-18 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_admin', '0004_delete_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
