# Generated by Django 5.1.6 on 2025-05-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0002_teacherprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
