# Generated by Django 5.1.6 on 2025-05-18 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0003_delete_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
