# Generated by Django 5.2.1 on 2025-05-20 01:04

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0004_customuser_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='lessons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
