# Generated by Django 5.1.6 on 2025-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_auth', '0002_customuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
